kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.16
    commands:
      - make linux
      - cp conf/importer-example.yml conf/importer.yml
      - make test
      - ./bin/gdg_linux version

trigger:
  event:
    - push
    - pull_request
---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: gh_secret
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

volumes:
  - name: deps
    temp: {}

