version: '3.8'
services:
    grafana-dashboard-manager:
        build:
            context: . 
        image: netsage/grafana-dashboard-manager:latest
        volumes:
          - ./conf:/opt/grafana-dashboard-manager/bin/conf

