version: '3.8'
services:
    grafana-dashboard-manager:
        build:
            context: . 
        image: safaci2000/grafana-dashboard-manager
        volumes:
          - ./importer.yml:/opt/grafana-dashboard-manager/bin/importer.yml

